# -*- coding: utf-8 -*-
"""Lab_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbmW0IouFThbcA2fbzD1WIK8BU_Lwssk
"""

!pip install transformers datasets -q

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

# Load data
dataset = load_dataset("imdb")
train = dataset["train"].select(range(100))

# Model
tokenizer = AutoTokenizer.from_pretrained("prajjwal1/bert-tiny")
model = AutoModelForSequenceClassification.from_pretrained("prajjwal1/bert-tiny", num_labels=2)

# FIXED tokenize
def tokenize(x):
    return tokenizer(
        x["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train = train.map(tokenize)

# IMPORTANT
train = train.rename_column("label", "labels")
train.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

# Train
args = TrainingArguments(
    output_dir="out",
    per_device_train_batch_size=8,
    num_train_epochs=1
)

trainer = Trainer(model=model, args=args, train_dataset=train)

trainer.train()

# =========================
# Install
# =========================
!pip install transformers datasets -q

# =========================
# Imports
# =========================
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForQuestionAnswering, Trainer, TrainingArguments

# =========================
# Load dataset (REAL)
# =========================
dataset = load_dataset("squad")

# small subset for fast run
train = dataset["train"].select(range(200))

# =========================
# Load model
# =========================
model_name = "prajjwal1/bert-tiny"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForQuestionAnswering.from_pretrained(model_name)

# =========================
# Preprocessing (REAL)
# =========================
def preprocess(example):
    inputs = tokenizer(
        example["question"],
        example["context"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

    start_positions = []
    end_positions = []

    for i in range(len(example["answers"])):
        start = example["answers"][i]["answer_start"][0]
        text = example["answers"][i]["text"][0]
        end = start + len(text)

        start_positions.append(start)
        end_positions.append(end)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions

    return inputs

# apply preprocessing
train = train.map(preprocess, batched=True)

# convert to torch
train.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "start_positions", "end_positions"]
)

# =========================
# Training
# =========================
args = TrainingArguments(
    output_dir="qa",
    per_device_train_batch_size=8,
    num_train_epochs=1,
    logging_steps=10
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train
)

trainer.train()

print("Lab 7 QA completed successfully")